In [23]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [24]:
from slc_rtc_lookup import query_slc_metadata_by_geometry, check_rtc_s1_by_many_slc_ids, check_rtc_s1_by_one_slc_id
from shapely.geometry import box
import pandas as pd
from datetime import datetime

In [25]:
la_bbox = None # box(-118.6682, 33.7037, -118.1553, 34.3373)
start = datetime(2026, 1, 15)
stop = datetime(2026, 1, 16)

In [26]:
df_slc = query_slc_metadata_by_geometry(geometry=la_bbox, 
                                        start_time=start, 
                                        stop_time=stop)
df_slc.head()

,slc_id,orbit_pass,slc_polarizations,track_number,start_time,url,s3_uri,size_gb,geometry
0,S1C_IW_SLC__1SDV_20260115T235307_20260115T2353...,DESCENDING,VV+VH,150,2026-01-15 23:53:07+00:00,https://datapool.asf.alaska.edu/SLC/SC/S1C_IW_...,s3://asf-ngap2w-p-s1-slc-7b420b89/S1C_IW_SLC__...,2.723255,"POLYGON ((92.74221 31.28839, 90.11195 31.69144..."
1,S1C_IW_SLC__1SDV_20260115T235242_20260115T2353...,DESCENDING,VV+VH,150,2026-01-15 23:52:42+00:00,https://datapool.asf.alaska.edu/SLC/SC/S1C_IW_...,s3://asf-ngap2w-p-s1-slc-7b420b89/S1C_IW_SLC__...,3.811765,"POLYGON ((93.08428 32.78365, 90.40742 33.18474..."
2,S1C_IW_SLC__1SDV_20260115T235217_20260115T2352...,DESCENDING,VV+VH,150,2026-01-15 23:52:17+00:00,https://datapool.asf.alaska.edu/SLC/SC/S1C_IW_...,s3://asf-ngap2w-p-s1-slc-7b420b89/S1C_IW_SLC__...,3.962351,"POLYGON ((93.41914 34.28009, 90.69755 34.6784,..."
3,S1C_IW_SLC__1SDV_20260115T235153_20260115T2352...,DESCENDING,VV+VH,150,2026-01-15 23:51:53+00:00,https://datapool.asf.alaska.edu/SLC/SC/S1C_IW_...,s3://asf-ngap2w-p-s1-slc-7b420b89/S1C_IW_SLC__...,3.822001,"POLYGON ((93.7746 35.7731, 90.99857 36.16999, ..."
4,S1C_IW_SLC__1SDV_20260115T235127_20260115T2351...,DESCENDING,VV+VH,150,2026-01-15 23:51:27+00:00,https://datapool.asf.alaska.edu/SLC/SC/S1C_IW_...,s3://asf-ngap2w-p-s1-slc-7b420b89/S1C_IW_SLC__...,4.105536,"POLYGON ((94.15968 37.32251, 91.31922 37.71883..."

In [27]:
slc_ids = df_slc['slc_id'].unique().tolist()
slc_ids[:3], df_slc.shape[0]

(['S1C_IW_SLC__1SDV_20260115T235307_20260115T235327_005921_00BDFD_9099',
  'S1C_IW_SLC__1SDV_20260115T235242_20260115T235309_005921_00BDFD_A2F4',
  'S1C_IW_SLC__1SDV_20260115T235217_20260115T235244_005921_00BDFD_1F6A'],
 927)

In [28]:
# df_rtc_check_one = check_rtc_s1_by_one_slc_id(slc_ids[0])
# df_rtc_check_one.head()

In [29]:
# df_rtc_check_one['rtc_opera_id'].isnull().sum()

In [30]:
df_rtc_check = check_rtc_s1_by_many_slc_ids(slc_ids)
df_rtc_check.head()

Checking RTC-S1 for SLCs:  10%|▉         | 89/927 [01:27<08:10,  1.71it/s] /Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T223411_20260115T223438_062784_07DFDC_531A found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  10%|▉         | 90/927 [01:29<13:57,  1.00s/it]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T223345_20260115T223413_062784_07DFDC_33D5 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  10%|█         | 93/927 [01:31<09:44,  1.43it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T222917_20260115T222950_062784_07DFDA_95DC found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T223318_20260115T223348_062784_07DFDC_B8EE found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  11%|█         | 98/927 [01:31<04:44,  2.91it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T222851_20260115T222919_062784_07DFDA_BF01 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  11%|█         | 100/927 [01:32<05:13,  2.64it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T222802_20260115T222829_062784_07DFDA_95A1 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T222712_20260115T222739_062784_07DFDA_622C found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  15%|█▍        | 136/927 [02:09<07:57,  1.65it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T213336_20260115T213404_062783_07DFD6_0AAA found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T213311_20260115T213338_062783_07DFD6_C25A found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  17%|█▋        | 158/927 [02:27<10:06,  1.27it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T204303_20260115T204332_005919_00BDED_24B6 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  17%|█▋        | 159/927 [02:30<15:52,  1.24s/it]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T204239_20260115T204305_005919_00BDED_02E0 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T204214_20260115T204241_005919_00BDED_DF20 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  18%|█▊        | 163/927 [02:33<11:05,  1.15it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T204149_20260115T204216_005919_00BDED_E807 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  18%|█▊        | 165/927 [02:34<10:59,  1.16it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T204124_20260115T204151_005919_00BDED_8A5D found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  18%|█▊        | 170/927 [02:36<06:31,  1.93it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T204056_20260115T204126_005919_00BDED_13AA found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  22%|██▏       | 201/927 [03:00<09:28,  1.28it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T190733_20260115T190800_062782_07DFC6_766A found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T190707_20260115T190735_062782_07DFC6_2418 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  22%|██▏       | 204/927 [03:02<08:05,  1.49it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T190640_20260115T190709_062782_07DFC6_9131 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  22%|██▏       | 205/927 [03:02<07:38,  1.57it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T183423_20260115T183446_005918_00BDE6_90A2 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T183216_20260115T183240_005918_00BDE5_A68E found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T183151_20260115T183218_005918_00BDE5_59E8 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T183101_20260115T183129_005918_00BDE5_7325 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  23%|██▎       | 213/927 [03:12<12:02,  1.01s/it]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T182921_20260115T182949_005918_00BDE5_6739 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  24%|██▍       | 222/927 [03:12<04:21,  2.69it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T182831_20260115T182858_005918_00BDE5_21DF found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T182856_20260115T182924_005918_00BDE5_FA44 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T182806_20260115T182833_005918_00BDE5_6812 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  25%|██▌       | 236/927 [03:26<09:25,  1.22it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T181604_20260115T181635_005918_00BDE4_C9EC found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T174510_20260115T174525_062781_07DFBC_DA7B found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T181633_20260115T181700_005918_00BDE4_FA2B found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  26%|██▌       | 239/927 [03:27<07:14,  1.58it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T174445_20260115T174512_062781_07DFBC_9D68 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T174240_20260115T174307_062781_07DFBC_1E0E found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  27%|██▋       | 252/927 [03:32<04:10,  2.70it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  30%|███       | 279/927 [03:55<08:08,  1.33it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1A_IW_SLC__1SDV_20260115T171707_20260115T171736_062780_07DFBA_74AE found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  30%|███       | 282/927 [03:56<05:55,  1.81it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T165639_20260115T165702_005917_00BDDE_5FAB found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T165614_20260115T165641_005917_00BDDE_C791 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
Checking RTC-S1 for SLCs:  31%|███       | 283/927 [03:57<08:21,  1.29it/s]/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T165525_20260115T165552_005917_00BDDE_E64A found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:133: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/slc-rtc-lookup/src/slc_rtc_lookup/slc_metadata.py:71: UserWarning: No bursts over land for SLC S1C_IW_SLC__1SDV_20260115T165549_20260115T165616_005917_00BDDE_FE80 found in LUT
  warn(f'No bursts over land for SLC {slc_id} found in LUT')

,burst_index,ogc_fid,sensing_time,slc_id,subswath,jpl_burst_id,relative_orbit_number,orbit_pass,rtc_opera_id,rtc_acq_dt,rtc_polarizations,rtc_track_number,rtc_pass_id,rtc_url_crosspol,rtc_url_copol,geometry,rtc_acq_date_for_mgrs_pass
0,0,320931,2026-01-15T23:53:08.370267,S1C_IW_SLC__1SDV_20260115T235307_20260115T2353...,IW1,T150-320931-IW1,150,DESCENDING,OPERA_L2_RTC-S1_T150-320931-IW1_20260115T23530...,2026-01-15 23:53:08+00:00,VV+VH,150,732,https://cumulus.asf.earthdatacloud.nasa.gov/OP...,https://cumulus.asf.earthdatacloud.nasa.gov/OP...,"POLYGON ((92.73343 31.2364, 91.77849 31.3895, ...",NaN
1,1,320932,2026-01-15T23:53:11.130879,S1C_IW_SLC__1SDV_20260115T235307_20260115T2353...,IW1,T150-320932-IW1,150,DESCENDING,OPERA_L2_RTC-S1_T150-320932-IW1_20260115T23531...,2026-01-15 23:53:11+00:00,VV+VH,150,732,https://cumulus.asf.earthdatacloud.nasa.gov/OP...,https://cumulus.asf.earthdatacloud.nasa.gov/OP...,"POLYGON ((92.69598 31.07005, 91.74402 31.22301...",NaN
2,2,320933,2026-01-15T23:53:13.891491,S1C_IW_SLC__1SDV_20260115T235307_20260115T2353...,IW1,T150-320933-IW1,150,DESCENDING,OPERA_L2_RTC-S1_T150-320933-IW1_20260115T23531...,2026-01-15 23:53:13+00:00,VV+VH,150,732,https://cumulus.asf.earthdatacloud.nasa.gov/OP...,https://cumulus.asf.earthdatacloud.nasa.gov/OP...,"POLYGON ((92.6586 30.90369, 91.70718 31.05688,...",NaN
3,3,320934,2026-01-15T23:53:16.643881,S1C_IW_SLC__1SDV_20260115T235307_20260115T2353...,IW1,T150-320934-IW1,150,DESCENDING,OPERA_L2_RTC-S1_T150-320934-IW1_20260115T23531...,2026-01-15 23:53:16+00:00,VV+VH,150,732,https://cumulus.asf.earthdatacloud.nasa.gov/OP...,https://cumulus.asf.earthdatacloud.nasa.gov/OP...,"POLYGON ((92.62138 30.73782, 91.66617 30.89192...",NaN
4,4,320935,2026-01-15T23:53:19.408604,S1C_IW_SLC__1SDV_20260115T235307_20260115T2353...,IW1,T150-320935-IW1,150,DESCENDING,OPERA_L2_RTC-S1_T150-320935-IW1_20260115T23531...,2026-01-15 23:53:19+00:00,VV+VH,150,732,https://cumulus.asf.earthdatacloud.nasa.gov/OP...,https://cumulus.asf.earthdatacloud.nasa.gov/OP...,"POLYGON ((92.58406 30.5712, 91.62998 30.72544,...",NaN

In [44]:
df_rtc_check_deduped = df_rtc_check.drop_duplicates(subset=['jpl_burst_id']).reset_index(drop=True)
f'Deduped: {df_rtc_check_deduped.shape[0]:,}, Original: {df_rtc_check.shape[0]:,}'

'Deduped: 20,341, Original: 40,682'

In [45]:
n_missing_products = df_rtc_check_deduped[df_rtc_check_deduped['rtc_opera_id'].isnull()].shape[0]
total_products_with_rtc = df_rtc_check_deduped.shape[0]

In [46]:
f'There are {n_missing_products:,} missing RTC S1 products out of {total_products_with_rtc:,} RTC-S1 products'

'There are 9,231 missing RTC S1 products out of 20,341 RTC-S1 products'

In [50]:
slc_ids_with_missing_rtc = df_rtc_check_deduped[df_rtc_check_deduped['rtc_opera_id'].isnull()]['slc_id'].unique().tolist()
total_slc_ids = len(df_rtc_check_deduped['slc_id'].unique().tolist())

In [51]:
f'There are {len(slc_ids_with_missing_rtc):,} SLC products with missing RTC S1 products out of {total_slc_ids} SLCs produced from {start.strftime("%Y%m%d")} to {stop.strftime("%Y%m%d")}'

'There are 394 SLC products with missing RTC S1 products out of 858 SLCs produced from 20260115 to 20260116'

In [52]:
df_rtc_check_deduped[df_rtc_check_deduped['rtc_opera_id'].isnull()].to_csv(f'missing_rtc_s1_prods_{start.strftime("%Y%m%d")}__{stop.strftime("%Y%m%d")}.csv')